#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nest_asyncio
Version  : 1.5.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/ad/82/2fdf6a92eed4ddf5e9d9a735d019af1ef3a56f084d9549972b2527a43a48/nest_asyncio-1.5.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/ad/82/2fdf6a92eed4ddf5e9d9a735d019af1ef3a56f084d9549972b2527a43a48/nest_asyncio-1.5.1.tar.gz
Summary  : Patch asyncio to allow nested event loops
Group    : Development/Tools
License  : BSD-2-Clause
Requires: nest_asyncio-license = %{version}-%{release}
Requires: nest_asyncio-python = %{version}-%{release}
Requires: nest_asyncio-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Introduction
        ------------

%package license
Summary: license components for the nest_asyncio package.
Group: Default

%description license
license components for the nest_asyncio package.


%package python
Summary: python components for the nest_asyncio package.
Group: Default
Requires: nest_asyncio-python3 = %{version}-%{release}

%description python
python components for the nest_asyncio package.


%package python3
Summary: python3 components for the nest_asyncio package.
Group: Default
Requires: python3-core
Provides: pypi(nest_asyncio)

%description python3
python3 components for the nest_asyncio package.


%prep
%setup -q -n nest_asyncio-1.5.1
cd %{_builddir}/nest_asyncio-1.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1612457214
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nest_asyncio
cp %{_builddir}/nest_asyncio-1.5.1/LICENSE %{buildroot}/usr/share/package-licenses/nest_asyncio/ca6c7502c84e9ca02bf0295d70a4b9d3c0488add
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nest_asyncio/ca6c7502c84e9ca02bf0295d70a4b9d3c0488add

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
